CONTIKI_PROJECT = udp-multicast udp-client udp-server
all: $(CONTIKI_PROJECT)

CONTIKI = /home/user/contiki-ng
MAKE_MAC = MAKE_MAC_TSCH

MODULES += os/services/shell
MODULES += os/services/simple-energest

include $(CONTIKI)/Makefile.include
